# Generated by Django 3.2.16 on 2024-06-16 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(related_name='subscribtions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('recipe', models.ManyToManyField(related_name='subscribtions', to='recipes.Recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'Подписки',
                'default_related_name': 'subscribtions',
            },
        ),
    ]
