# Generated by Django 3.2.16 on 2024-07-09 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_change_sub_name_add_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfIngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_of_ingredient', to='recipes.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_of_ingredient', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'количество ингредента в рецепте',
                'verbose_name_plural': 'Количество ингредиентов в рецепте',
                'default_related_name': 'amount_of_ingredient',
            },
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='amount_of_ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='AmountOfIngredient',
        ),
        migrations.DeleteModel(
            name='IngredientInRecipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.AmountOfIngredientInRecipe', to='recipes.Ingredient', verbose_name='Ингредиенты в рецепте'),
        ),
    ]
