# Generated by Django 3.2.16 on 2024-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_change_amount_ingredient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amountofingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_in_recipe'),
        ),
    ]
